### ISSUE TITLE
"%.1f" of 999.99 => "999.0"

### ISSUE THREAD

**Issue by NicholasWMRitchie** [tjol/sprintf-rs#2]
Incorrect rounding of floating point numbers:

`sprintf!("%.1f",999.99).unwrap() == "999.0" `

should be "1000.0"

**Comment by tjol** [comment]
Well spotted! I don't think just replacing `trunc` with `round` will work (that'll probably turn 1.5 into 1.5 or something), but you're on the right track

**Comment by NicholasWMRitchie** [comment]
Of course, you are correct.  `round(...)` replacing `trunc(...)` won't fix it.
Maybe, rounding the number to the correct number of decimal places above `trunc(...)` might.
