### ISSUE TITLE
Support C string types

### ISSUE THREAD

**Issue by flaviojs** [tjol/sprintf-rs#6]
I tried to use this crate with C string pointers but failed.

Are you ok with implementing `sprintf::Printf` for:
* `std::ffi::CStr`
* `std::ffi::CString`
* `*const c_char`
* `*mut c_char`
* `c_char` too if possible

I don't mind having to enable a feature flag.

**Comment by tjol** [comment]
Treating `*const c_char` as a string is a non-starter, but I'm open to *considering* `CStr` and `CString`. I'd like to understand the use case, though.

* Can't you just convert the C strings to `&str` using the [`to_str`](https://doc.rust-lang.org/std/ffi/struct.CStr.html#method.to_str) method?
* What sort of environment are you in where you have to operate on C strings but you can't or don't want to use the 'real [`snprintf`](https://docs.rs/libc/latest/libc/fn.snprintf.html) from libc?

**Comment by flaviojs** [comment]
I'm converting code from C to rust bit by bit. There is lots of code, in the current stage I'm trying to stay as close to the unsafe original as possible to avoid introducing new bugs. At a later stage I'll be converting unsafe code to safe code.

Right now I'm working on a function that needs `vsnprintf` in the original code.
VaList is not available in stable rust. So I'm exploring what I can use now and later (needs C-like format).

Rust does not allow me to implement sprintf::Printf for std types, so here I am asking if it's ok to implement them here.

**Comment by tjol** [comment]
I see,  that makes sense.

This is (and will remain) a safe crate, so treating `*const c_char` and `*mut c_char` as strings is out of the question. Implementations of `Printf` for `CStr` and `CString` would be ok (`OSStr` and `OSString` too, perhaps?). They'd need to check that the strings are UTF-8, of course (by calling `to_str`).

Are all your strings UTF-8? If they're not, you'd probably need an snprintf function that returns `CString` or `Vec<u8>`.

If you need to support `*const c_char` (which I'm guessing you probably do?), maybe you can write an unsafe wrapper function, something like this:

```rust
trait UnsafeIntoPrintf {
    unsafe fn into_printf_unchecked(&self) -> BoxOrRef<dyn Printf + '_>;
}

enum BoxOrRef<'lt, T: ?Sized> {
    Box(Box<T>),
    Ref(&'lt T)
}

unsafe fn vsprintf_c(format: &str, args: &[&dyn UnsafeIntoPrintf]) -> sprintf::Result<String> {
    let boxes = args.iter().map(|arg| arg.into_printf_unchecked()).collect::<Vec<_>>();
    let refs = boxes.iter().map(|b| b.as_ref()).collect::<Vec<_>>();
    sprintf::vsprintf(format, &refs)
}

impl<'lt, T: ?Sized> BoxOrRef<'lt, T> {
    fn as_ref(&self) -> &T {
        match self {
            BoxOrRef::Box(b) => b.as_ref(),
            BoxOrRef::Ref(r) => r
        }
    }
}

impl UnsafeIntoPrintf for i32 {
    unsafe fn into_printf_unchecked(&self) -> BoxOrRef<dyn Printf + '_> {
        BoxOrRef::Ref(self)
    }
}

impl UnsafeIntoPrintf for &CStr {
    unsafe fn into_printf_unchecked(&self) -> BoxOrRef<dyn Printf + '_> {
        BoxOrRef::Box(Box::new(std::str::from_utf8_unchecked(self.to_bytes())))
    }
}

impl UnsafeIntoPrintf for CStr {
    unsafe fn into_printf_unchecked(&self) -> BoxOrRef<dyn Printf + '_> {
        BoxOrRef::Box(Box::new(std::str::from_utf8_unchecked(self.to_bytes())))
    }
}

impl UnsafeIntoPrintf for *const c_char {
    unsafe fn into_printf_unchecked(&self) -> BoxOrRef<dyn Printf + '_> {
        CStr::from_ptr(*self).into_printf()
    }
}

```

If just CStr and CString (without the pointer types, and with the UTF-8 check in `CStr::to_str`) is useful to you, feel free to prepare a patch/PR.

I'm also happy to allow `i8` (= `c_char`) and possibly `u16` and `u32` as inputs for `%c`, in addition to `char`.

**Comment by flaviojs** [comment]
Thanks for the implementation reference.
Yes, they will be useful for me so I made a PR.
