### ISSUE TITLE
Print pointer addresses

### ISSUE THREAD

**Issue by flaviojs** [tjol/sprintf-rs#8]
I'm converting a printf-like call from C to rust that uses `%p` to print the address of a pointer but currently pointers are not supported in this library.

The `p` conversion type is parsed and the address of a pointer is safe data so it should be fine to accept a pointer.
Is this the case? I can make a PR.

Alternatively maybe you want users to require an explicit cast to usize (or .addr() with strict_provenance).
Is this the case? If so, the docs should be updated to reflect that.

**Comment by tjol** [comment]
Sure, that makes sense. I see no reason `%p` shouldn't work with `*const  T` and `*mut T`.
